name: "PR Label Check"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [master]

jobs:
  check-label:
    uses: heitorpolidoro/.github/.github/workflows/pr-label-check.yml@master
