name: "Release"

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  release:
    uses: heitorpolidoro/.github/.github/workflows/release.yml@master
    with:
      working_directory: frontend
      version_command: "npm version $BUMP_TYPE --no-git-tag-version"
      version_files: "frontend/package.json frontend/package-lock.json"
    secrets: inherit
